name: Docker Image CI

on:
  push:
    branches:
      - "main"

jobs:
  build-back:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:backend"
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64  # Spécifie les architectures
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest

  build-front:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:frontend"
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64  # Spécifie les architectures
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest